-- Canonicalize departments + relink employees (plain SQL, no DO block).
-- Generated: 2026-04-30T14:35:02

-- 1. Trim whitespace on all department names
UPDATE departments SET name = trim(name) WHERE name <> trim(name);

-- 2. For each CSV department, ensure exactly one canonical row

-- Brand
INSERT INTO departments (company_id, name) SELECT (SELECT id FROM companies ORDER BY created_at LIMIT 1), 'Brand' WHERE NOT EXISTS (SELECT 1 FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Brand'));
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Brand') ORDER BY (name = 'Brand') DESC, created_at DESC LIMIT 1) WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Brand'));
UPDATE departments SET parent_department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Brand') ORDER BY (name = 'Brand') DESC, created_at DESC LIMIT 1) WHERE parent_department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Brand'));
DELETE FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Brand') AND id <> (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Brand') ORDER BY (name = 'Brand') DESC, created_at DESC LIMIT 1);
UPDATE departments SET name = 'Brand' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Brand') AND name <> 'Brand';

-- Business Development
INSERT INTO departments (company_id, name) SELECT (SELECT id FROM companies ORDER BY created_at LIMIT 1), 'Business Development' WHERE NOT EXISTS (SELECT 1 FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Business Development'));
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Business Development') ORDER BY (name = 'Business Development') DESC, created_at DESC LIMIT 1) WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Business Development'));
UPDATE departments SET parent_department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Business Development') ORDER BY (name = 'Business Development') DESC, created_at DESC LIMIT 1) WHERE parent_department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Business Development'));
DELETE FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Business Development') AND id <> (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Business Development') ORDER BY (name = 'Business Development') DESC, created_at DESC LIMIT 1);
UPDATE departments SET name = 'Business Development' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Business Development') AND name <> 'Business Development';

-- Corporate Services
INSERT INTO departments (company_id, name) SELECT (SELECT id FROM companies ORDER BY created_at LIMIT 1), 'Corporate Services' WHERE NOT EXISTS (SELECT 1 FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Corporate Services'));
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Corporate Services') ORDER BY (name = 'Corporate Services') DESC, created_at DESC LIMIT 1) WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Corporate Services'));
UPDATE departments SET parent_department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Corporate Services') ORDER BY (name = 'Corporate Services') DESC, created_at DESC LIMIT 1) WHERE parent_department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Corporate Services'));
DELETE FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Corporate Services') AND id <> (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Corporate Services') ORDER BY (name = 'Corporate Services') DESC, created_at DESC LIMIT 1);
UPDATE departments SET name = 'Corporate Services' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Corporate Services') AND name <> 'Corporate Services';

-- Executive
INSERT INTO departments (company_id, name) SELECT (SELECT id FROM companies ORDER BY created_at LIMIT 1), 'Executive' WHERE NOT EXISTS (SELECT 1 FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Executive'));
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Executive') ORDER BY (name = 'Executive') DESC, created_at DESC LIMIT 1) WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Executive'));
UPDATE departments SET parent_department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Executive') ORDER BY (name = 'Executive') DESC, created_at DESC LIMIT 1) WHERE parent_department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Executive'));
DELETE FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Executive') AND id <> (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Executive') ORDER BY (name = 'Executive') DESC, created_at DESC LIMIT 1);
UPDATE departments SET name = 'Executive' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Executive') AND name <> 'Executive';

-- Finance
INSERT INTO departments (company_id, name) SELECT (SELECT id FROM companies ORDER BY created_at LIMIT 1), 'Finance' WHERE NOT EXISTS (SELECT 1 FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Finance'));
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Finance') ORDER BY (name = 'Finance') DESC, created_at DESC LIMIT 1) WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Finance'));
UPDATE departments SET parent_department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Finance') ORDER BY (name = 'Finance') DESC, created_at DESC LIMIT 1) WHERE parent_department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Finance'));
DELETE FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Finance') AND id <> (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Finance') ORDER BY (name = 'Finance') DESC, created_at DESC LIMIT 1);
UPDATE departments SET name = 'Finance' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Finance') AND name <> 'Finance';

-- Growth
INSERT INTO departments (company_id, name) SELECT (SELECT id FROM companies ORDER BY created_at LIMIT 1), 'Growth' WHERE NOT EXISTS (SELECT 1 FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Growth'));
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Growth') ORDER BY (name = 'Growth') DESC, created_at DESC LIMIT 1) WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Growth'));
UPDATE departments SET parent_department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Growth') ORDER BY (name = 'Growth') DESC, created_at DESC LIMIT 1) WHERE parent_department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Growth'));
DELETE FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Growth') AND id <> (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Growth') ORDER BY (name = 'Growth') DESC, created_at DESC LIMIT 1);
UPDATE departments SET name = 'Growth' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Growth') AND name <> 'Growth';

-- HR
INSERT INTO departments (company_id, name) SELECT (SELECT id FROM companies ORDER BY created_at LIMIT 1), 'HR' WHERE NOT EXISTS (SELECT 1 FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('HR'));
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('HR') ORDER BY (name = 'HR') DESC, created_at DESC LIMIT 1) WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('HR'));
UPDATE departments SET parent_department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('HR') ORDER BY (name = 'HR') DESC, created_at DESC LIMIT 1) WHERE parent_department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('HR'));
DELETE FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('HR') AND id <> (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('HR') ORDER BY (name = 'HR') DESC, created_at DESC LIMIT 1);
UPDATE departments SET name = 'HR' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('HR') AND name <> 'HR';

-- Marketing
INSERT INTO departments (company_id, name) SELECT (SELECT id FROM companies ORDER BY created_at LIMIT 1), 'Marketing' WHERE NOT EXISTS (SELECT 1 FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Marketing'));
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Marketing') ORDER BY (name = 'Marketing') DESC, created_at DESC LIMIT 1) WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Marketing'));
UPDATE departments SET parent_department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Marketing') ORDER BY (name = 'Marketing') DESC, created_at DESC LIMIT 1) WHERE parent_department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Marketing'));
DELETE FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Marketing') AND id <> (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Marketing') ORDER BY (name = 'Marketing') DESC, created_at DESC LIMIT 1);
UPDATE departments SET name = 'Marketing' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Marketing') AND name <> 'Marketing';

-- Medical
INSERT INTO departments (company_id, name) SELECT (SELECT id FROM companies ORDER BY created_at LIMIT 1), 'Medical' WHERE NOT EXISTS (SELECT 1 FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Medical'));
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Medical') ORDER BY (name = 'Medical') DESC, created_at DESC LIMIT 1) WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Medical'));
UPDATE departments SET parent_department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Medical') ORDER BY (name = 'Medical') DESC, created_at DESC LIMIT 1) WHERE parent_department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Medical'));
DELETE FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Medical') AND id <> (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Medical') ORDER BY (name = 'Medical') DESC, created_at DESC LIMIT 1);
UPDATE departments SET name = 'Medical' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Medical') AND name <> 'Medical';

-- Medical Research
INSERT INTO departments (company_id, name) SELECT (SELECT id FROM companies ORDER BY created_at LIMIT 1), 'Medical Research' WHERE NOT EXISTS (SELECT 1 FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Medical Research'));
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Medical Research') ORDER BY (name = 'Medical Research') DESC, created_at DESC LIMIT 1) WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Medical Research'));
UPDATE departments SET parent_department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Medical Research') ORDER BY (name = 'Medical Research') DESC, created_at DESC LIMIT 1) WHERE parent_department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Medical Research'));
DELETE FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Medical Research') AND id <> (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Medical Research') ORDER BY (name = 'Medical Research') DESC, created_at DESC LIMIT 1);
UPDATE departments SET name = 'Medical Research' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Medical Research') AND name <> 'Medical Research';

-- Operations
INSERT INTO departments (company_id, name) SELECT (SELECT id FROM companies ORDER BY created_at LIMIT 1), 'Operations' WHERE NOT EXISTS (SELECT 1 FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Operations'));
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Operations') ORDER BY (name = 'Operations') DESC, created_at DESC LIMIT 1) WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Operations'));
UPDATE departments SET parent_department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Operations') ORDER BY (name = 'Operations') DESC, created_at DESC LIMIT 1) WHERE parent_department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Operations'));
DELETE FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Operations') AND id <> (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Operations') ORDER BY (name = 'Operations') DESC, created_at DESC LIMIT 1);
UPDATE departments SET name = 'Operations' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Operations') AND name <> 'Operations';

-- Tech
INSERT INTO departments (company_id, name) SELECT (SELECT id FROM companies ORDER BY created_at LIMIT 1), 'Tech' WHERE NOT EXISTS (SELECT 1 FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Tech'));
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Tech') ORDER BY (name = 'Tech') DESC, created_at DESC LIMIT 1) WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Tech'));
UPDATE departments SET parent_department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Tech') ORDER BY (name = 'Tech') DESC, created_at DESC LIMIT 1) WHERE parent_department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Tech'));
DELETE FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Tech') AND id <> (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Tech') ORDER BY (name = 'Tech') DESC, created_at DESC LIMIT 1);
UPDATE departments SET name = 'Tech' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND lower(trim(name)) = lower('Tech') AND name <> 'Tech';

-- 3. Drop legacy departments not in the CSV
UPDATE employees SET department_id = NULL WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND department_id IN (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name NOT IN ('Brand', 'Business Development', 'Corporate Services', 'Executive', 'Finance', 'Growth', 'HR', 'Marketing', 'Medical', 'Medical Research', 'Operations', 'Tech'));
DELETE FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name NOT IN ('Brand', 'Business Development', 'Corporate Services', 'Executive', 'Finance', 'Growth', 'HR', 'Marketing', 'Medical', 'Medical Research', 'Operations', 'Tech');

-- 4. Force-link each employee to the canonical department row
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Executive' LIMIT 1), department = 'Executive' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0001';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Executive' LIMIT 1), department = 'Executive' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0002';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Brand' LIMIT 1), department = 'Brand' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0003';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Growth' LIMIT 1), department = 'Growth' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0005';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Operations' LIMIT 1), department = 'Operations' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0016';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Tech' LIMIT 1), department = 'Tech' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0018';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Marketing' LIMIT 1), department = 'Marketing' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0040';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Executive' LIMIT 1), department = 'Executive' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0041';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'HR' LIMIT 1), department = 'HR' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0042';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Corporate Services' LIMIT 1), department = 'Corporate Services' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0043';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Operations' LIMIT 1), department = 'Operations' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0045';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Finance' LIMIT 1), department = 'Finance' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0049';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Marketing' LIMIT 1), department = 'Marketing' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0051';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Operations' LIMIT 1), department = 'Operations' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0056';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Operations' LIMIT 1), department = 'Operations' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0058';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Marketing' LIMIT 1), department = 'Marketing' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0061';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Marketing' LIMIT 1), department = 'Marketing' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0063';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Tech' LIMIT 1), department = 'Tech' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0065';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Tech' LIMIT 1), department = 'Tech' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0066';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Corporate Services' LIMIT 1), department = 'Corporate Services' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0067';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Operations' LIMIT 1), department = 'Operations' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0071';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Marketing' LIMIT 1), department = 'Marketing' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0073';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Executive' LIMIT 1), department = 'Executive' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0074';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Operations' LIMIT 1), department = 'Operations' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0076';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Operations' LIMIT 1), department = 'Operations' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0080';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Tech' LIMIT 1), department = 'Tech' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0081';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Medical' LIMIT 1), department = 'Medical' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0088';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Operations' LIMIT 1), department = 'Operations' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0091';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Operations' LIMIT 1), department = 'Operations' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0092';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Growth' LIMIT 1), department = 'Growth' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0093';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Tech' LIMIT 1), department = 'Tech' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0094';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Business Development' LIMIT 1), department = 'Business Development' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0096';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Growth' LIMIT 1), department = 'Growth' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0102';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Operations' LIMIT 1), department = 'Operations' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0103';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Medical Research' LIMIT 1), department = 'Medical Research' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0104';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Corporate Services' LIMIT 1), department = 'Corporate Services' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0105';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Medical' LIMIT 1), department = 'Medical' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = 'F001';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Medical' LIMIT 1), department = 'Medical' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0082';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Medical' LIMIT 1), department = 'Medical' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0083';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Medical' LIMIT 1), department = 'Medical' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0084';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Medical' LIMIT 1), department = 'Medical' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0085';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Medical' LIMIT 1), department = 'Medical' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0087';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Medical' LIMIT 1), department = 'Medical' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = 'F002';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Medical' LIMIT 1), department = 'Medical' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0097';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Medical' LIMIT 1), department = 'Medical' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0098';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Medical' LIMIT 1), department = 'Medical' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0099';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Medical' LIMIT 1), department = 'Medical' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = '0100';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Medical' LIMIT 1), department = 'Medical' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = 'F003';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Medical' LIMIT 1), department = 'Medical' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = 'F004';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Medical' LIMIT 1), department = 'Medical' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = 'F005';
UPDATE employees SET department_id = (SELECT id FROM departments WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND name = 'Medical' LIMIT 1), department = 'Medical' WHERE company_id = (SELECT id FROM companies ORDER BY created_at LIMIT 1) AND employee_number = 'F006';
