"use client";

import { useEffect, useState, useCallback } from "react";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface DailyTimeRecord {
  id: string;
  date: string;
  first_in: string | null;
  last_out: string | null;
  total_hours_worked: number | null;
  regular_hours: number | null;
  night_diff_hours: number | null;
  late_minutes: number | null;
  undertime_minutes: number | null;
  is_rest_day: boolean;
  is_holiday: boolean;
  holiday_type: string | null;
  status: "computed" | "adjusted" | "approved";
  employee_id: string;
  schedule_id: string | null;
  employee: {
    id: string;
    name: string;
    employee_number?: string;
    department_id: string | null;
  } | null;
}

interface Department {
  id: string;
  name: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Get the current semi-monthly period boundaries. */
function getSemiMonthlyPeriod(): { from: string; to: string } {
  const today = new Date();
  const year = today.getFullYear();
  const month = today.getMonth();
  const day = today.getDate();

  if (day <= 15) {
    const from = new Date(year, month, 1);
    const to = new Date(year, month, 15);
    return { from: fmt(from), to: fmt(to) };
  } else {
    const from = new Date(year, month, 16);
    const to = new Date(year, month + 1, 0); // last day of month
    return { from: fmt(from), to: fmt(to) };
  }
}

function fmt(d: Date): string {
  return d.toISOString().split("T")[0];
}

function formatShortDate(dateStr: string): string {
  const d = new Date(dateStr + "T00:00:00");
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

function formatTime(timeStr: string | null): string {
  if (!timeStr) return "—";
  // timeStr could be "HH:mm:ss" or an ISO timestamp
  const d = timeStr.includes("T") ? new Date(timeStr) : new Date(`1970-01-01T${timeStr}`);
  if (isNaN(d.getTime())) return timeStr;
  return d.toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  });
}

function formatHours(val: number | null): string {
  if (val == null) return "—";
  return val.toFixed(2);
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function AttendancePage() {
  const period = getSemiMonthlyPeriod();

  const [records, setRecords] = useState<DailyTimeRecord[]>([]);
  const [departments, setDepartments] = useState<Department[]>([]);
  const [loading, setLoading] = useState(true);
  const [computing, setComputing] = useState(false);
  const [approving, setApproving] = useState(false);
  const [message, setMessage] = useState<string | null>(null);

  // Filters
  const [from, setFrom] = useState(period.from);
  const [to, setTo] = useState(period.to);
  const [departmentId, setDepartmentId] = useState("");
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [showMoot, setShowMoot] = useState(false);

  // Edit-clock modal state — handles both clock-in and clock-out edits
  const [editTarget, setEditTarget] = useState<DailyTimeRecord | null>(null);
  const [editField, setEditField] = useState<"first_in" | "last_out">("last_out");
  const [editValue, setEditValue] = useState("");
  const [editSaving, setEditSaving] = useState(false);
  const [editError, setEditError] = useState("");

  // ---------------------------------------------------------------------------
  // Data fetching
  // ---------------------------------------------------------------------------

  const fetchRecords = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams({ from, to });
      if (departmentId) params.set("department_id", departmentId);
      const res = await fetch(`/api/dtr?${params}`);
      if (res.ok) {
        const data = await res.json();
        setRecords(data);
      }
    } finally {
      setLoading(false);
    }
  }, [from, to, departmentId]);

  useEffect(() => {
    fetch("/api/departments")
      .then((r) => r.json())
      .then((d) => setDepartments(d))
      .catch(() => {});
  }, []);

  useEffect(() => {
    fetchRecords();
  }, [fetchRecords]);

  // ---------------------------------------------------------------------------
  // Filtered records
  // ---------------------------------------------------------------------------

  // A row is "moot" when there's nothing to look at: no clock data, no
  // schedule, not a rest day, not a holiday. These get auto-generated by
  // the batch compute for every employee × day in the range and just clutter
  // the view. Hidden by default; toggle to see them.
  const isMoot = (r: DailyTimeRecord) =>
    !r.first_in &&
    !r.last_out &&
    (r.total_hours_worked ?? 0) === 0 &&
    !r.is_rest_day &&
    !r.is_holiday &&
    !r.schedule_id &&
    r.status === "computed";

  const filtered = records.filter((r) => {
    if (!showMoot && isMoot(r)) return false;
    if (statusFilter !== "all" && r.status !== statusFilter) return false;
    if (search) {
      const q = search.toLowerCase();
      const name = r.employee?.name?.toLowerCase() ?? "";
      const num = r.employee?.employee_number?.toLowerCase() ?? "";
      if (!name.includes(q) && !num.includes(q)) return false;
    }
    return true;
  });

  const mootCount = records.filter(isMoot).length;

  // ---------------------------------------------------------------------------
  // Summary stats
  // ---------------------------------------------------------------------------

  const totalRecords = filtered.length;
  const avgHours =
    totalRecords > 0
      ? filtered.reduce((sum, r) => sum + (r.total_hours_worked ?? 0), 0) / totalRecords
      : 0;
  const totalLateHours =
    filtered.reduce((sum, r) => sum + (r.late_minutes ?? 0), 0) / 60;
  const totalUndertimeHours =
    filtered.reduce((sum, r) => sum + (r.undertime_minutes ?? 0), 0) / 60;

  // ---------------------------------------------------------------------------
  // Actions
  // ---------------------------------------------------------------------------

  const handleCompute = async () => {
    setComputing(true);
    setMessage(null);
    try {
      const res = await fetch("/api/dtr", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ from, to }),
      });
      if (res.ok) {
        const data = await res.json();
        setMessage(`Computed ${data.computed} records`);
        await fetchRecords();
      } else {
        const err = await res.json();
        setMessage(`Error: ${err.error}`);
      }
    } catch {
      setMessage("Failed to compute DTR");
    } finally {
      setComputing(false);
    }
  };

  // ---- Edit clock-in / clock-out -------------------------------------------

  function openEditModal(r: DailyTimeRecord, field: "first_in" | "last_out") {
    setEditTarget(r);
    setEditField(field);
    setEditError("");
    const iso = field === "first_in" ? r.first_in : r.last_out;
    if (iso) {
      const d = new Date(iso);
      const hh = String(d.getHours()).padStart(2, "0");
      const mm = String(d.getMinutes()).padStart(2, "0");
      setEditValue(`${hh}:${mm}`);
    } else {
      setEditValue("");
    }
  }

  function closeEditModal() {
    setEditTarget(null);
    setEditValue("");
    setEditError("");
  }

  async function saveEdit() {
    if (!editTarget) return;
    if (!editValue) {
      setEditError(`Pick a ${editField === "first_in" ? "clock-in" : "clock-out"} time`);
      return;
    }
    setEditSaving(true);
    try {
      const [hh, mm] = editValue.split(":").map(Number);
      const [y, m, d] = editTarget.date.split("-").map(Number);
      const local = new Date(y, m - 1, d, hh, mm, 0, 0);
      const localIso = local.toISOString();

      const updates: Record<string, unknown> = { [editField]: localIso };

      // Recompute total_hours_worked using the OTHER endpoint as fixed.
      const otherIso =
        editField === "first_in" ? editTarget.last_out : editTarget.first_in;

      if (otherIso) {
        const inMs =
          editField === "first_in" ? local.getTime() : new Date(otherIso).getTime();
        const outMs =
          editField === "first_in" ? new Date(otherIso).getTime() : local.getTime();

        if (outMs <= inMs) {
          setEditError("Clock-out must be after clock-in");
          setEditSaving(false);
          return;
        }
        const hours = Math.round(((outMs - inMs) / 3_600_000) * 100) / 100;
        updates.total_hours_worked = hours;
        updates.regular_hours = Math.min(hours, 8);
      }

      const res = await fetch(`/api/dtr/${editTarget.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(updates),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Failed to update");

      closeEditModal();
      await fetchRecords();
    } catch (err) {
      setEditError(err instanceof Error ? err.message : "Failed to update");
    } finally {
      setEditSaving(false);
    }
  }

  const handleBulkApprove = async () => {
    const approvable = filtered.filter(
      (r) => r.status === "computed" || r.status === "adjusted",
    );
    if (approvable.length === 0) {
      setMessage("No records to approve");
      return;
    }
    if (!confirm(`Approve ${approvable.length} records?`)) return;

    setApproving(true);
    setMessage(null);
    let approved = 0;
    for (const record of approvable) {
      try {
        const res = await fetch(`/api/dtr/${record.id}`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ action: "approve" }),
        });
        if (res.ok) approved++;
      } catch {}
    }
    setMessage(`Approved ${approved} of ${approvable.length} records`);
    await fetchRecords();
    setApproving(false);
  };

  // ---------------------------------------------------------------------------
  // Status badge
  // ---------------------------------------------------------------------------

  function StatusBadge({ status }: { status: string }) {
    const styles: Record<string, { bg: string; text: string }> = {
      computed: { bg: "rgba(28, 26, 22, 0.06)", text: "var(--color-sw-ink-500)" },
      adjusted: { bg: "rgba(207,147,88,0.15)", text: "var(--color-sw-gold-600)" },
      approved: { bg: "rgba(34,139,34,0.10)", text: "var(--color-sw-success-500)" },
    };
    const s = styles[status] ?? styles.computed;
    return (
      <span
        className="inline-block text-xs font-medium px-2.5 py-0.5 rounded-full capitalize"
        style={{ background: s.bg, color: s.text }}
      >
        {status}
      </span>
    );
  }

  // ---------------------------------------------------------------------------
  // Render
  // ---------------------------------------------------------------------------

  return (
    <div>
      {/* Header */}
      <div className="flex justify-between items-center mb-6">
        <h1 className="t-display">
          Attendance
        </h1>
        <div className="flex gap-3">
          <button
            onClick={handleBulkApprove}
            disabled={approving}
            className="px-5 py-2.5 rounded-full text-sm font-medium border border-sw-ink-200 text-sw-ink-700 bg-white hover:bg-[var(--color-sw-ink-100)] transition-all duration-150 disabled:opacity-50"
          >
            {approving ? "Approving..." : "Bulk Approve"}
          </button>
          <button
            onClick={handleCompute}
            disabled={computing}
            className="px-5 py-2.5 rounded-full text-sm font-medium text-[#ffffff] transition-all duration-150 hover:shadow-[0_4px_24px_var(--color-sw-ink-200)] disabled:opacity-50"
            style={{ background: "var(--color-sw-gold-500)" }}
          >
            {computing ? "Computing..." : "Compute DTR"}
          </button>
        </div>
      </div>

      {/* Success / error message */}
      {message && (
        <div className="mb-4 px-4 py-3 rounded-xl bg-white border border-sw-ink-100 text-sm text-sw-ink-700">
          {message}
        </div>
      )}

      {/* Filters */}
      <div className="flex flex-wrap gap-3 mb-6">
        <div className="flex items-center gap-2">
          <label className="text-xs text-sw-ink-500 uppercase tracking-wide">
            From
          </label>
          <input
            type="date"
            value={from}
            onChange={(e) => setFrom(e.target.value)}
            className="h-10 px-3 bg-sw-cream-50 border border-sw-ink-200 rounded-xl text-sm text-sw-ink-900 focus:outline-none focus:ring-2 focus:ring-[rgba(201, 151, 46, 0.22)]"
          />
        </div>
        <div className="flex items-center gap-2">
          <label className="text-xs text-sw-ink-500 uppercase tracking-wide">
            To
          </label>
          <input
            type="date"
            value={to}
            onChange={(e) => setTo(e.target.value)}
            className="h-10 px-3 bg-sw-cream-50 border border-sw-ink-200 rounded-xl text-sm text-sw-ink-900 focus:outline-none focus:ring-2 focus:ring-[rgba(201, 151, 46, 0.22)]"
          />
        </div>
        <select
          value={departmentId}
          onChange={(e) => setDepartmentId(e.target.value)}
          className="h-10 px-3 bg-sw-cream-50 border border-sw-ink-200 rounded-xl text-sm text-sw-ink-700 focus:outline-none focus:ring-2 focus:ring-[rgba(201, 151, 46, 0.22)]"
        >
          <option value="">All Departments</option>
          {departments.map((d) => (
            <option key={d.id} value={d.id}>
              {d.name}
            </option>
          ))}
        </select>
        <input
          type="text"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search employee..."
          className="h-10 px-3 bg-sw-cream-50 border border-sw-ink-200 rounded-xl text-sm text-sw-ink-900 placeholder:text-sw-ink-300 focus:outline-none focus:ring-2 focus:ring-[rgba(201, 151, 46, 0.22)] min-w-[180px]"
        />
        <select
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value)}
          className="h-10 px-3 bg-sw-cream-50 border border-sw-ink-200 rounded-xl text-sm text-sw-ink-700 focus:outline-none focus:ring-2 focus:ring-[rgba(201, 151, 46, 0.22)]"
        >
          <option value="all">All Statuses</option>
          <option value="computed">Computed</option>
          <option value="adjusted">Adjusted</option>
          <option value="approved">Approved</option>
        </select>
        {mootCount > 0 && (
          <label className="flex items-center gap-2 px-3 h-10 rounded-xl border border-sw-ink-200 bg-sw-cream-50 text-sm text-sw-ink-700 cursor-pointer">
            <input
              type="checkbox"
              checked={showMoot}
              onChange={(e) => setShowMoot(e.target.checked)}
            />
            Show {mootCount} empty
          </label>
        )}
      </div>

      {/* Summary stats */}
      <div className="grid grid-cols-4 gap-4 mb-6">
        {[
          { label: "Total Records", value: totalRecords.toString() },
          { label: "Avg Hours", value: formatHours(avgHours) },
          { label: "Total Late", value: `${totalLateHours.toFixed(1)}h` },
          { label: "Total Undertime", value: `${totalUndertimeHours.toFixed(1)}h` },
        ].map((stat) => (
          <div
            key={stat.label}
            className="glass-card rounded-2xl px-5 py-4"
          >
            <p className="text-xs text-sw-ink-500 uppercase tracking-wide mb-1">
              {stat.label}
            </p>
            <p className="text-xl font-medium text-sw-ink-900">
              {stat.value}
            </p>
          </div>
        ))}
      </div>

      {/* Table */}
      {loading ? (
        <div className="flex items-center justify-center h-64">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-sw-gold-500" />
        </div>
      ) : filtered.length === 0 ? (
        <div className="sw-panel p-16 text-center">
          <p className="text-base text-sw-ink-500">
            {records.length === 0
              ? "No DTR records found for this period. Click \"Compute DTR\" to generate."
              : "No records match your filters."}
          </p>
        </div>
      ) : (
        <div className="sw-panel overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="text-left bg-sw-cream-25 border-b border-sw-ink-100">
                  {[
                    "Employee",
                    "Date",
                    "Schedule",
                    "In",
                    "Out",
                    "Hours",
                    "Regular",
                    "Night Diff",
                    "Late",
                    "Undertime",
                    "Status",
                  ].map((col) => (
                    <th
                      key={col}
                      className="px-4 py-3 text-xs font-medium uppercase tracking-wide text-sw-ink-500 whitespace-nowrap"
                    >
                      {col}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {filtered.map((r) => (
                  <tr
                    key={r.id}
                    className="border-b border-sw-ink-100 last:border-0 hover:bg-sw-cream-25 transition-colors duration-150"
                  >
                    <td className="px-6 py-4">
                      <span className="text-sm font-medium text-sw-ink-900">
                        {r.employee?.name ?? "—"}
                      </span>
                      {r.employee?.employee_number && (
                        <span className="ml-1.5 text-xs text-sw-ink-300">
                          #{r.employee.employee_number}
                        </span>
                      )}
                    </td>
                    <td className="px-6 py-4 text-sm text-sw-ink-700 whitespace-nowrap">
                      {formatShortDate(r.date)}
                    </td>
                    <td className="px-6 py-4 text-sm text-sw-ink-700">
                      {r.is_rest_day
                        ? "Rest Day"
                        : r.is_holiday
                          ? r.holiday_type ?? "Holiday"
                          : r.schedule_id
                            ? "Regular"
                            : "—"}
                    </td>
                    <td className="px-6 py-4 text-sm whitespace-nowrap">
                      <button
                        type="button"
                        onClick={(e) => {
                          e.stopPropagation();
                          openEditModal(r, "first_in");
                        }}
                        title="Click to edit clock-in"
                        className={`group inline-flex items-center gap-1.5 px-2.5 py-1 -mx-2.5 -my-1 rounded-lg border border-dashed transition-colors cursor-pointer ${
                          r.first_in
                            ? "border-transparent text-sw-ink-700 hover:bg-[var(--color-sw-gold-50)] hover:border-[var(--color-sw-gold-500)] hover:text-sw-gold-600"
                            : "border-sw-ink-200 text-sw-ink-300 hover:bg-[var(--color-sw-gold-50)] hover:border-[var(--color-sw-gold-500)] hover:text-sw-gold-600"
                        }`}
                      >
                        {r.first_in ? formatTime(r.first_in) : "+ set"}
                        <svg
                          className="w-3 h-3 opacity-0 group-hover:opacity-70 transition-opacity"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth={2}
                        >
                          <path strokeLinecap="round" strokeLinejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931z" />
                        </svg>
                      </button>
                    </td>
                    <td className="px-6 py-4 text-sm whitespace-nowrap">
                      <button
                        type="button"
                        onClick={(e) => {
                          e.stopPropagation();
                          openEditModal(r, "last_out");
                        }}
                        title="Click to edit clock-out"
                        className={`group inline-flex items-center gap-1.5 px-2.5 py-1 -mx-2.5 -my-1 rounded-lg border border-dashed transition-colors cursor-pointer ${
                          r.last_out
                            ? "border-transparent text-sw-ink-700 hover:bg-[var(--color-sw-gold-50)] hover:border-[var(--color-sw-gold-500)] hover:text-sw-gold-600"
                            : "border-sw-ink-200 text-sw-ink-300 hover:bg-[var(--color-sw-gold-50)] hover:border-[var(--color-sw-gold-500)] hover:text-sw-gold-600"
                        }`}
                      >
                        {r.last_out ? formatTime(r.last_out) : "+ set"}
                        <svg
                          className="w-3 h-3 opacity-0 group-hover:opacity-70 transition-opacity"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth={2}
                        >
                          <path strokeLinecap="round" strokeLinejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931z" />
                        </svg>
                      </button>
                    </td>
                    <td className="px-6 py-4 text-sm text-sw-ink-900 font-medium">
                      {formatHours(r.total_hours_worked)}
                    </td>
                    <td className="px-6 py-4 text-sm text-sw-ink-700">
                      {formatHours(r.regular_hours)}
                    </td>
                    <td className="px-6 py-4 text-sm text-sw-ink-700">
                      {formatHours(r.night_diff_hours)}
                    </td>
                    <td className="px-6 py-4 text-sm whitespace-nowrap">
                      <span
                        className={
                          (r.late_minutes ?? 0) > 0
                            ? "text-red-600 font-medium"
                            : "text-sw-ink-500"
                        }
                      >
                        {r.late_minutes != null ? `${r.late_minutes}m` : "—"}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-sm whitespace-nowrap">
                      <span
                        className={
                          (r.undertime_minutes ?? 0) > 0
                            ? "text-red-600 font-medium"
                            : "text-sw-ink-500"
                        }
                      >
                        {r.undertime_minutes != null
                          ? `${r.undertime_minutes}m`
                          : "—"}
                      </span>
                    </td>
                    <td className="px-6 py-4">
                      <StatusBadge status={r.status} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Edit clock-in / clock-out modal */}
      {editTarget && (
        <>
          <div className="fixed inset-0 bg-black/30 z-40" onClick={closeEditModal} />
          <div className="fixed inset-0 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-2xl shadow-xl w-full max-w-sm p-6">
              <h2 className="text-lg font-semibold text-sw-ink-900 mb-1">
                Adjust {editField === "first_in" ? "Clock-In" : "Clock-Out"}
              </h2>
              <p className="text-sm text-sw-ink-500 mb-4">
                <span className="font-medium">{editTarget.employee?.name ?? "—"}</span> · {formatShortDate(editTarget.date)}
              </p>

              {/* Show the OTHER endpoint for context */}
              {editField === "first_in" && editTarget.last_out && (
                <div className="text-xs text-sw-ink-500 mb-3 px-3 py-2 rounded-lg bg-sw-cream-25">
                  Clocked out: <span className="font-medium text-sw-ink-700">{formatTime(editTarget.last_out)}</span>
                </div>
              )}
              {editField === "last_out" && editTarget.first_in && (
                <div className="text-xs text-sw-ink-500 mb-3 px-3 py-2 rounded-lg bg-sw-cream-25">
                  Clocked in: <span className="font-medium text-sw-ink-700">{formatTime(editTarget.first_in)}</span>
                </div>
              )}

              <label className="block text-sm font-medium text-sw-ink-700 mb-1">
                {editField === "first_in" ? "Clock-in time" : "Clock-out time"}
              </label>
              <input
                type="time"
                value={editValue}
                onChange={(e) => setEditValue(e.target.value)}
                className="w-full h-10 px-3 rounded-xl border border-sw-ink-200 text-sm focus:outline-none focus:ring-2 focus:ring-[var(--color-sw-gold-500)]"
              />
              <p className="text-xs text-sw-ink-500 mt-1">
                Hours worked will be recomputed automatically.
              </p>

              {editError && (
                <div className="mt-3 px-3 py-2 rounded-xl bg-red-50 text-red-700 text-xs">
                  {editError}
                </div>
              )}

              <div className="flex justify-end gap-3 mt-6">
                <button
                  onClick={closeEditModal}
                  className="px-4 py-2 rounded-full text-sm font-medium text-sw-ink-700 hover:bg-[var(--color-sw-ink-100)]"
                >
                  Cancel
                </button>
                <button
                  onClick={saveEdit}
                  disabled={editSaving}
                  className="px-5 py-2 rounded-full text-sm font-medium text-white disabled:opacity-50"
                  style={{ background: "var(--color-sw-gold-500)" }}
                >
                  {editSaving ? "Saving..." : "Save"}
                </button>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
